### PR TITLE
Chore: add metafiles

### PR DESCRIPTION
**Pull request by FaGru3n**
#### What would be changed or will be added with this PR?
- add initial metafiles
#### Why do i want to change this?
- https://github.com/eclipse-tractusx/sig-infra/issues/143

### CODE REVIEW

**Review by tomaszbarwicki — COMMENTED** [review]
@FaGru3n is that a new requirement that catenax-ng repos follow TRGs?

**Comment by FaGru3n** [comment]
@tomaszbarwicki no not really, just want to prepare the repo for eventually moving into the "other" GitHub Organisation.
see mentioned issue

**Review by tomaszbarwicki — APPROVED** [review]
LGTM

**Review by almadigabor — APPROVED** [review]
LGTM

**Pull request merged**
